version: '3.2'
volumes:
  mysql_1:
    external: true
services:
  mysql_1:
    container_name: mysql_1
    image: mysql:latest
    privileged: true
    user: root
    restart: always
    ports:
      - 5442:3306
    env_file:
      - mysql_1.env
    volumes:
      - mysql_1:/var/lib/mysql
    # depends_on:
    # - XXXX
    networks:
      - net
  phpmyadmin_1:
    container_name: phpmyadmin_1
    image: phpmyadmin:latest
    privileged: true
    user: root
    restart: always
    ports:
      - 5441:80
    env_file:
      - phpmyadmin_1.env
    # depends_on:
    # - XXXX
    networks:
      - net
networks:
  net:
    name: net
